// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eczmumeybuilbwoghcwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjem11bWV5YnVpbGJ3b2doY3dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MDYwMzMsImV4cCI6MjA2MDM4MjAzM30.0XOVeH7svDmsXRgjmiMWdqCOXLu3-_GP4JaQVFx48ZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);